ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        always_run: true
      - id: check-json
        exclude: ^\.devcontainer/devcontainer\.json
        always_run: true
      - id: end-of-file-fixer
        always_run: true
      - id: trailing-whitespace
        always_run: true
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-merge-conflict
      - id: pretty-format-json
        exclude: ^\.devcontainer/devcontainer\.json
        args: [--autofix, --no-ensure-ascii]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.2.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        name: Ansible Lint
        description: Run configurations on .ansible-lint file
        verbose: true
        # args: [-p, ./ansible/*]
