---
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '25 11 5 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test using Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_args: -d docker
